name: Security Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * 1" # Weekly security scan

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install detect-secrets

      - name: Run detect-secrets scan
        run: |
          detect-secrets scan > .secrets.baseline.new
          # Check if there are new secrets not in the baseline
          if ! diff .secrets.baseline .secrets.baseline.new > /dev/null 2>&1; then
            echo "New secrets detected! Please review and update the baseline if needed."
            diff .secrets.baseline .secrets.baseline.new || true
            exit 1
          fi

      - name: Check for hardcoded secrets
        run: |
          # Look for common secret patterns
          SECRET_PATTERNS=("api[key|_key]" "secret" "token" "password" "jwt" "bearer")
          FOUND_SECRETS=false
          for pattern in "${SECRET_PATTERNS[@]}"; do
            if grep -r -i -n --exclude-dir=.git "$pattern[[:space:]]*=[[:space:]]*['\"][^'\"]\{10,\}['\"]" .; then
              FOUND_SECRETS=true
            fi
          done
          if [ "$FOUND_SECRETS" = true ]; then
            echo "Hardcoded secrets detected! Please use environment variables instead."
            exit 1
          fi
